apiVersion: v1
kind: Service
metadata:
  name: socket-service
  labels:
    app: {{ .Values.spec.template.metadata.labels.app }}
spec:
  type: ClusterIP
  selector: 
    app: {{ .Values.spec.template.metadata.labels.app }}
  ports:
  - port: 7000
    targetPort: 7000
