version: 0.2

phases:
  install:
    commands:
      # Install Helm 3
      - echo Installing Helm...
      - curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION:-us-east-1} | docker login --username AWS --password-stdin 003304347306.dkr.ecr.us-east-1.amazonaws.com
      - cd Infisign-PAM-BE/infisign-socket
      - chmod +x update_version.sh
      - ./update_version.sh staging
      - source /tmp/codebuild_env
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 003304347306.dkr.ecr.us-east-1.amazonaws.com/be-microservice:infisign-socket-staging -f Dockerfile .
      - docker tag 003304347306.dkr.ecr.us-east-1.amazonaws.com/be-microservice:infisign-socket-staging 003304347306.dkr.ecr.us-east-1.amazonaws.com/be-microservice:infisign-socket-$version
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images to ECR...
      - docker push 003304347306.dkr.ecr.us-east-1.amazonaws.com/be-microservice:infisign-socket-staging
      - docker push 003304347306.dkr.ecr.us-east-1.amazonaws.com/be-microservice:infisign-socket-$version
      - echo Deploying Helm Chart...
      # Update kubeconfig to access the EKS cluster
      - aws eks update-kubeconfig --region ${AWS_DEFAULT_REGION:-us-east-1} --name ent-eks-prod
      - cd ../Charts/infisign-socket
      - helm upgrade --install infisign-socket . --set image.tag=infisign-socket-$version --namespace ${NAMESPACE:-mid-staging}
